language: php
#node_js:
#- 13.12.0
#before_install: cd E:\Docker\ProyectoIC
#cache: 
#directories:
#- E:\Docker\ProyectoIC\node_modules

#install:
#- npm install

#script:
#- npm run-script build

deploy:
provider: master
skip_cleanup: true
github_token: $GITHUB_TOKEN
#local_dir:. ProyectoIC
on:
branch: master