language: node_js
node_js:
- "12.14.0"
before_install: cd E:\Docker\ProyectoIC
cache: npm
#directories:
#- E:\Docker\ProyectoIC\node_modules

install:
- npm install

script:
- npm test
- npm run build
#- npm run-script build

deploy:
provider: pages
skip_cleanup: true
github_token: $GITHUB_TOKEN
local_dir: ProyectoIC
on:
branch: master